os:
  - osx
  - linux
dist: trusty
sudo: false
language: generic
install:
  - . ./install-tex.sh
script:
  - latex -v
  - ./tlmgr.sh --version
  - ./tlmgr.sh update --self --all || echo "ignore errors"
  - ./tlmgr.sh install collection-langjapanese
  - platex -v
